--<ScriptOptions statementTerminator=";"/>

CREATE TABLE MEMO_SET_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		MEMO_SET_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_TAG_TYPE_KEY SMALLINT,
		PARENT_TAG_PID SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE ENCODING_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		ENCODING_TYPE_DEFN_PID INTEGER NOT NULL,
		IS_IMPORT_TYPE BOOLEAN,
		IS_INTERNAL_TYPE BOOLEAN,
		IS_EXPORT_TYPE BOOLEAN,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE NAME_ELMNT_INPUT_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NAME_ELMNT_INPUT_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		ENTITY_TYPE_KEY SMALLINT,
		ENTITY_SUB_TYPE_KEY SMALLINT,
		PARENT_NAME_STYLE_KEY SMALLINT,
		NAME_ELMNT_TYPE_KEY SMALLINT,
		DATA_TYPE_KEY SMALLINT,
		FIELD_RANK_ORDER SMALLINT,
		VALID_SCRIPT_GROUP_KEY SMALLINT,
		VALID_SCRIPT_KEY SMALLINT,
		LEFT_FIELD_ELMNT_KEY SMALLINT,
		RIGHT_FIELD_ELMNT_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		IS_DETAIL_ELMNT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE UNITS_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		UNITS_DEFN_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSET_PAIR_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSET_PAIR_PID INTEGER NOT NULL,
		SUBSET_PID INTEGER,
		USE_ORDER INTEGER,
		REFER1_PID INTEGER,
		REFER2_PID INTEGER
	);

CREATE TABLE VIEWPOINT_ELEMENTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		VIEWPOINT_ELEMENT_PID INTEGER NOT NULL,
		VIEWPOINT_PID INTEGER,
		SCREEN_CONFIG_PID SMALLINT,
		IS_MASTER BOOLEAN,
		IS_SECOND_COPY BOOLEAN,
		AUTO_UPDATE BOOLEAN,
		SHOW_ON_OPEN BOOLEAN
	);

CREATE TABLE NAMED_MEMO_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NAMED_MEMO_TYPE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_TAG_TYPE_KEY SMALLINT,
		PARENT_TAG_TYPE_PID SMALLINT,
		REMINDER_KEY INTEGER,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE CITN_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		CITN_TYPE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		VIEW_DATA_SCRIPT_GROUP_KEY SMALLINT,
		VIEW_DATA_SCRIPT_PID INTEGER,
		MODIFY_DATA_SCRIPT_GROUP_KEY SMALLINT,
		MODIFY_DATA_SCRIPT_PID INTEGER,
		DELETE_DATA_SCRIPT_GROUP_KEY SMALLINT,
		DELETE_DATA_SCRIPT_PID INTEGER,
		CITING_TYPE_KEY SMALLINT,
		CITING_SUB_TYPE_KEY SMALLINT,
		GEDCOM_TAG VARCHAR(30),
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE GUI_LANGUAGES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		GUI_LANGUAGE_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		GUI_LANGUAGE VARCHAR(4),
		DATA1_LANGUAGE VARCHAR(4),
		DATA2_LANGUAGE VARCHAR(4),
		REPORT_LANGUAGE VARCHAR(4),
		DFLT_LANGUAGE VARCHAR(4)
	);

CREATE TABLE HDATES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		HDATE_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		IS_HUMAN_CALENDAR BOOLEAN,
		HDATE1 BIGINT,
		HDATE2 BIGINT,
		SORT_HDATE1 BIGINT,
		SORT_HDATE2 BIGINT,
		ORIGINAL_TEXT VARCHAR(160),
		LANG_CODE VARCHAR(4),
		HDATE_TYPE_KEY SMALLINT,
		NAMED_MEMO_PID INTEGER,
		SURETY VARCHAR(10)
	);

CREATE TABLE BIO_ETHNICITY_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		BIO_ETHNICITY_DEFN_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE FIELD_VALID_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FIELD_VALID_DEFN_PID INTEGER NOT NULL,
		VIEW_SCRIPT_GROUP_KEY SMALLINT,
		VIEW_SCRIPT_PID INTEGER,
		MODIFY_SCRIPT_GROUP_KEY SMALLINT,
		MODIFY_SCRIPT_PID INTEGER,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SENTENCE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SENTENCE_TEMPLATE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PLUGIN_KEY SMALLINT,
		SENTENCE_SET_KEY SMALLINT,
		SENTCE_STYLE_TYPE_KEY SMALLINT,
		REQUESTER_TYPE_KEY SMALLINT,
		REQUESTER_SUB_TYPE_KEY SMALLINT,
		REQUESTER_PID INTEGER,
		PUBLISH_TYPE_KEY SMALLINT
	);

CREATE TABLE SESSIONS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SESSION_PID INTEGER NOT NULL,
		PROJECT_PID INTEGER,
		USER_PID INTEGER,
		TIME_OPENED TIMESTAMP,
		TIME_CLOSED TIMESTAMP,
		COMMIT_NUM INTEGER
	);

CREATE TABLE TEMPLATE_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		TEMPLATE_TYPE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		IS_MANDATORY BOOLEAN,
		ENTITY_TYPE_KEY SMALLINT,
		ENTITY_SUB_TYPE_KEY SMALLINT,
		PUBLISH_TYPE_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE ROLE_PAIR_NAME_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		ROLE_PAIR_NAME_TRAN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PLUGIN_KEY SMALLINT,
		TAG_KEY SMALLINT,
		LANG_CODE VARCHAR(4),
		ROLE_A_TO_B VARCHAR(60),
		ROLE_B_TO_A VARCHAR(60)
	);

CREATE TABLE FIELD_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY INTEGER NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FIELD_DEFN_PID INTEGER NOT NULL,
		VERSION_NAME VARCHAR(300),
		SQL_NAME VARCHAR(30),
		SQL_TYPE VARCHAR(30),
		DATA_TYPE_KEY SMALLINT,
		ENCODE_TYPE_KEY SMALLINT,
		FIELD_FORMAT_KEY SMALLINT,
		FIELD_VALID_KEY SMALLINT,
		FIELD_RECENT_PID INTEGER,
		MAX_RECENT SMALLINT,
		MAX_FIXED SMALLINT,
		LEFT_FIELD_PID INTEGER,
		RIGHT_FIELD_PID INTEGER,
		HAS_AUTO_FILLIN BOOLEAN,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE USERS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		USER_PID INTEGER NOT NULL,
		LOGON_NAME VARCHAR(100),
		USER_NAME VARCHAR(100),
		PASSWORD VARCHAR(100),
		EMAIL VARCHAR(100),
		USER_TYPE_PID INTEGER,
		USER_GROUP_PID INTEGER
	);

CREATE TABLE BIO_KIN_TERM_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		BIO_KIN_TERM_DEFN_PID INTEGER NOT NULL,
		CURRENT_IS_FEMALE BOOLEAN,
		FOCUS_IS_FEMALE BOOLEAN,
		THIS_GENERATION SMALLINT,
		REMOVED_GENERATION SMALLINT,
		KIN_ETHNICITY_KEY SMALLINT,
		ANCESTOR_KIN_CODE VARCHAR(8),
		DESCENDANT_KIN_CODE VARCHAR(8),
		KIN_TERM_TRANS_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE OCCASN_OCCASN_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		OCCASN_OCCASN_TAG_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		VIEW_DATA_SCRIPT_GROUP_KEY SMALLINT,
		VIEW_DATA_SCRIPT_PID INTEGER,
		MODIFY_DATA_SCRIPT_GROUP_KEY SMALLINT,
		MODIFY_DATA_SCRIPT_PID INTEGER,
		DELETE_DATA_SCRIPT_GROUP_KEY SMALLINT,
		DELETE_DATA_SCRIPT_PID INTEGER,
		A_OCCASN_SUB_TYPE_KEY SMALLINT,
		B_OCCASN_SUB_TYPE_KEY SMALLINT,
		A_B_ROLE_NAME_PAIR_KEY SMALLINT,
		A_SENTCE_SET_PID INTEGER,
		B_SENTCE_SET_PID INTEGER,
		TAG_GROUP_KEY SMALLINT,
		THEME_KEY SMALLINT,
		GEDCOM_TAG VARCHAR(30),
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SCRIPT_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SCRIPT_TRAN_PID INTEGER NOT NULL,
		PARENT_PID INTEGER,
		LANG_CODE VARCHAR(4),
		SCRIPT VARCHAR(32000)
	);

CREATE TABLE GUI_SCREEN_CONFIGS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		GUI_SCREEN_CONFIG_PID INTEGER NOT NULL,
		PLUGIN_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE NAME_OUT_TEMPLATE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NAME_OUT_TEMPLATE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_NAME_STYLE_TYPE_KEY SMALLINT,
		TEMPLATE_TYPE_KEY SMALLINT,
		SORTING_ONLY BOOLEAN,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE LIST_OBJECT_SETS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LIST_OBJECT_SET_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		INPUT_TYPE_KEY SMALLINT,
		INPUT_SUB_TYPE_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE OCCASN_TIMELINE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER,
		OCCASN_TIMELINE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		OCCASN_SUB_TYPE_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE BIO_NAME_MAPS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		BIO_NAME_MAP_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_NAME_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		ELEMENT_TYPE_KEY SMALLINT,
		SHARED INTEGER,
		INFERRED_SHARED INTEGER
	);

CREATE TABLE MEMO_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		MEMO_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PLUGIN_KEY SMALLINT,
		MEMO_SET_KEY SMALLINT,
		REQUESTER_TYPE_KEY SMALLINT,
		REQUESTER_SUB_TYPE_KEY SMALLINT,
		REQUESTER_PID INTEGER,
		PUBLISH_TYPE_KEY SMALLINT
	);

CREATE TABLE OCCASN_BTWN_ASSOC_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		OCCASN_BTWN_ASSOC_TAG_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		VIEW_DATA_SCRIPT_GROUP_KEY SMALLINT,
		VIEW_DATA_SCRIPT_PID INTEGER,
		MODIFY_DATA_SCRIPT_GROUP_KEY SMALLINT,
		MODIFY_DATA_SCRIPT_PID INTEGER,
		DELETE_DATA_SCRIPT_GROUP_KEY SMALLINT,
		DELETE_DATA_SCRIPT_PID INTEGER,
		OCCASN_SUB_TYPE_KEY SMALLINT,
		ASSOC_A_TYPE_KEY SMALLINT,
		ASSOC_A_SUB_TYPE_KEY SMALLINT,
		ASSOC_B_TYPE_KEY SMALLINT,
		ASSOC_B_SUB_TYPE_KEY SMALLINT,
		ROLE_PAIR_KEY SMALLINT,
		TAG_GROUP_KEY SMALLINT,
		THEME_KEY SMALLINT,
		SENTCE_STYLE_TYPE_KEY SMALLINT,
		A_SUBJ_SENTCE_SET_KEY INTEGER,
		B_SUBJ_SENTCE_SET_KEY INTEGER,
		GEDCOM_TAG VARCHAR(30),
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE PLUGIN_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PLUGIN_DEFN_PID INTEGER NOT NULL,
		IS_NATIVE BOOLEAN,
		VERSON_NAME VARCHAR(160),
		PARENT_PCKG_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSTN_PARAM_NAMES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_PARAM_NAME_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		VIEW_DATA_SCRIPT_GROUP_KEY SMALLINT,
		VIEW_DATA_SCRIPT_PID INTEGER,
		MODIFY_DATA_SCRIPT_GROUP_KEY SMALLINT,
		MODIFY_DATA_SCRIPT_PID INTEGER,
		DELETE_DATA_SCRIPT_GROUP_KEY SMALLINT,
		DELETE_DATA_SCRIPT_PID INTEGER,
		EVAL_DATA_SCRIPT_GROUP_KEY SMALLINT,
		EVAL_DATA_SCRIPT_PID INTEGER,
		PARAM_SET_KEY SMALLINT,
		DATA_TYPE_KEY SMALLINT,
		MUST_BE_ENTERED BOOLEAN,
		DEFLT_VALUE VARCHAR(300),
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE GUI_SCREEN_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		GUI_SCREEN_DEFN_PID INTEGER NOT NULL,
		PLUGIN_KEY SMALLINT,
		TOP_ELEMENT SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSET_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSET_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		SUBSET_TYPE_KEY SMALLINT,
		SIZE INTEGER,
		STACK_INDEX INTEGER,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER INTEGER,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE ROLE_NAME_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		ROLE_NAME_TRAN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PLUGIN_KEY SMALLINT,
		TAG_KEY SMALLINT,
		LANG_CODE VARCHAR(4),
		ROLE VARCHAR(60)
	);

CREATE TABLE SCRIPT_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SCRIPT_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		ACTION_TYPE_KEY SMALLINT,
		INPUT_FOCUS_TYPE_KEY SMALLINT,
		INPUT_SUB_TYPE_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE DIGITALS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		DIGITAL_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		VISIBLE_ID INTEGER,
		SUB_TYPE_KEY SMALLINT,
		BEST_NAME_PID INTEGER,
		BEST_CREATE_PID INTEGER,
		BEST_DESTROY_PID INTEGER,
		BEST_IMAGE_PID INTEGER,
		SURETY VARCHAR(10),
		IS_INTERNAL BOOLEAN,
		IS_BINARY BOOLEAN,
		BINARY_CONTENT BLOB(2147483647),
		CHAR_CONTENT CLOB(2147483647),
		FILE_PATH VARCHAR(300),
		PATH_IS_FULL BOOLEAN,
		ENCODING_KEY SMALLINT,
		IMAGE_WIDTH SMALLINT,
		IMAGE_HEIGHT SMALLINT,
		EDITED_COPY_PID INTEGER,
		FLAGS VARBINARY(100)
	);

CREATE TABLE BIO_KIN_TERM_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		BIO_KIN_TERM_TRAN_PID INTEGER NOT NULL,
		KIN_ETHNICITY_KEY SMALLINT,
		KIN_TERM_HAS_SUBSTN BOOLEAN,
		LANG_CODE VARCHAR(4),
		KIN_TERM VARCHAR(100)
	);

CREATE TABLE ENTITY_NAME_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		ENTITY_NAME_TAG_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PLUGIN_PID SMALLINT,
		VIEW_DATA_SCRIPT_GROUP_KEY SMALLINT,
		VIEW_DATA_SCRIPT_PID INTEGER,
		MODIFY_DATA_SCRIPT_GROUP_KEY SMALLINT,
		MODIFY_DATA_SCRIPT_PID INTEGER,
		DELETE_DATA_SCRIPT_GROUP_KEY SMALLINT,
		DELETE_DATA_SCRIPT_PID INTEGER,
		ENTITY_TYPE_KEY SMALLINT,
		ENTITY_SUB_TYPE_KEY SMALLINT,
		DFLT_SENTCE_SET_KEY SMALLINT,
		DFLT_TAG_GROUP_KEY SMALLINT,
		DFLT_THEME_KEY SMALLINT,
		SENTCE_SET_TYPE_KEY SMALLINT,
		SENTCE_STYLE_TYPE_KEY SMALLINT,
		GLOBAL_SENTCE_SET_KEY SMALLINT,
		MEMO_SET_TYPE_KEY SMALLINT,
		HAS_MULTI_PART BOOLEAN,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE PHYSICAL_NOTEPADS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PHYSICAL_NOTEPAD_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		NOTEPAD_DEFN_PID SMALLINT,
		NOTEPAD VARCHAR(32000)
	);

CREATE TABLE FLAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FLAG_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_TYPE_KEY SMALLINT,
		PARENT_SUB_TYPE_KEY SMALLINT,
		FLAG_SLOT SMALLINT,
		STATES SMALLINT,
		DFLT_STATE SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SEX_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SEX_DEFN_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE OCCASNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER,
		OCCASN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		TAG_TYPE_KEY SMALLINT,
		THEME_VISIBLE_ID INTEGER,
		PARENT_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		THEME_KEY SMALLINT,
		LOCAL_SENTCE_SET_PID INTEGER,
		BEST_NAME_PID INTEGER,
		BEST_IMAGE_PID INTEGER,
		SURETY VARCHAR(10),
		SENTCE_TYPE_KEY SMALLINT,
		SENTCE_STYLE_KEY SMALLINT,
		BIO_PARENT_SET_PID INTEGER,
		MEMO_SET_PID INTEGER,
		FLAGS VARBINARY(100)
	);

CREATE TABLE DIGITAL_NAMES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		DIGITAL_NAME_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_SUB_TYPE_KEY SMALLINT,
		PARENT_PID INTEGER,
		NAME_TAG_KEY SMALLINT,
		NAME_STYLE_KEY SMALLINT,
		ELEMENTS_ENTERED VARBINARY(8),
		THIS_HDATE_PID INTEGER,
		THIS_NAME_EVENT_PID INTEGER,
		THIS_HDATE_INFERRED BOOLEAN,
		NEXT_HDATE_PID INTEGER,
		NEXT_NAME_EVENT_PID INTEGER,
		NEXT_HDATE_INFERRED BOOLEAN,
		THEME_KEY SMALLINT,
		SENTCE_SET_KEY INTEGER,
		SENTCE_TYPE_KEY SMALLINT,
		SENTCE_STYLE_KEY SMALLINT,
		MEMO_SET_PID INTEGER
	);

CREATE TABLE USER_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		USER_TYPE_DEFN_PID INTEGER NOT NULL,
		IS_USER_DEFN BOOLEAN,
		POOR_EYESIGHT BOOLEAN,
		IS_COLORBLIND BOOLEAN,
		MIN_MOUSE_USE BOOLEAN,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE LANGUAGE_NAME_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LANGUAGE_NAME_TRAN_PID INTEGER NOT NULL,
		TO_LANGUAGE VARCHAR(4),
		FROM_LANGUAGE VARCHAR(4),
		TRANSLATION VARCHAR(60)
	);

CREATE TABLE SCHEMA_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SCHEMA_DEFN_PID INTEGER NOT NULL,
		VERSION_NAME VARCHAR(160) NOT NULL,
		MAIN_PCKG_KEY SMALLINT NOT NULL,
		REMINDER_KEY SMALLINT NOT NULL,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE PHYSICAL_NAME_MAPS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PHYSICAL_NAME_MAP_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_NAME_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		ELEMENT_TYPE_KEY SMALLINT,
		SHARED INTEGER,
		INFERRED_SHARED INTEGER
	);

CREATE TABLE ENTITY_SUB_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		ENTITY_SUB_TYPE_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		BASE_ENTITY_TYPE_KEY SMALLINT,
		BASE_ENTITY_SUB_TYPE_KEY SMALLINT,
		PARENT_SUB_TYPE_KEY SMALLINT,
		GROUP_OF_TYPE_KEY SMALLINT,
		GROUP_OF_SUB_TYPE_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE OUTPUT_TEMPLATE_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		OUTPUT_TEMPLATE_TRAN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PLUGIN_KEY SMALLINT,
		ENTITY_TYPE_KEY SMALLINT,
		SUB_TYPE_KEY SMALLINT,
		SENTCE_STYLE_TYPE_KEY SMALLINT,
		NAME_STYLE_KEY SMALLINT,
		TEMPLATE_TYPE_KEY SMALLINT,
		LANG_CODE VARCHAR(4),
		TEMPLATE VARCHAR(4000)
	);

CREATE TABLE SENTENCE_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SENTENCE_TYPE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		REQUESTER_TYPE_KEY SMALLINT,
		REQUESTER_SUB_TYPE_KEY SMALLINT,
		REQUESTER_TYPE_PID SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE OCCASN_ASSOC_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		OCCASN_ASSOC_TAG_DEFN_PID INTEGER NOT NULL,
		IS_USER_DEFN BOOLEAN,
		OCCASN_SUB_TYPE_KEY SMALLINT,
		OCCASN_TAG_TYPE_KEY SMALLINT,
		ASSOC_TYPE_KEY SMALLINT,
		ASSOC_SUB_TYPE_KEY SMALLINT,
		ROLE_NAME_KEY SMALLINT,
		MIN_IN_ROLE SMALLINT,
		MAX_IN_ROLE SMALLINT,
		IS_REQUIRED_ROLE BOOLEAN,
		GROUP_KEY SMALLINT,
		THEME_KEY SMALLINT,
		SENTCE_SET_PID INTEGER,
		SENTCE_STYLE_TYPE_KEY SMALLINT,
		TAG_RULE_KEY SMALLINT,
		GEDCOM_TAG VARCHAR(30),
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE BIO_NAMES (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		COMMIT_PID INTEGER,
		BIO_NAME_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		NAME_TAG_KEY SMALLINT,
		NAME_STYLE_KEY SMALLINT,
		ELEMENTS_ENTERED VARBINARY(8),
		THIS_HDATE_PID INTEGER,
		THIS_NAME_EVENT_PID INTEGER,
		THIS_HDATE_INFERRED BOOLEAN,
		NEXT_HDATE_PID INTEGER,
		NEXT_NAME_EVENT_PID INTEGER,
		NEXT_HDATE_INFERRED BOOLEAN,
		THEME_KEY SMALLINT,
		SENTCE_SET_KEY SMALLINT,
		SENTCE_TYPE_KEY SMALLINT,
		SENTCE_STYLE_KEY SMALLINT,
		MEMO_SET_PID INTEGER
	);

CREATE TABLE THEME_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		THEME_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PLUGIN_KEY SMALLINT,
		ENTITY_TYPE_KEY SMALLINT,
		ENTITY_SUB_TYPE_KEY SMALLINT,
		IS_MAIN_THEME BOOLEAN,
		MAIN_THEME_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSTN_STEPS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_STEP_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_IS_DATA_ALIAS BOOLEAN,
		OWNER_TYPE_KEY SMALLINT,
		OWNER_SUB_TYPE_KEY INTEGER,
		OWNER_PID INTEGER,
		PARENT_STEP_PID INTEGER,
		PLAIN_TEXT VARCHAR(32767),
		NORMAL_START_STEP_PID INTEGER,
		FALSE_START_STEP_PID INTEGER,
		ERROR_STEP_PID INTEGER,
		PRIOR_STEP_PID INTEGER,
		NEXT_STEP_PID INTEGER,
		IS_TEMPLATE_STEP_TYPE BOOLEAN,
		IS_FILTER_STEP_TYPE BOOLEAN,
		STEP_TYPE_KEY SMALLINT,
		PARAM_LIST_KEY SMALLINT
	);

CREATE TABLE SUBSET_FILTER_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSET_FILTER_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		INPUT_TYPE_KEY SMALLINT,
		INPUT_SUB_TYPE_KEY SMALLINT,
		OUTPUT_TYPE_KEY SMALLINT,
		OUTPUT_SUB_TYPE_KEY SMALLINT,
		START_STEP_PID SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSTN_PARAM_VALUES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_PARAM_VALUE_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_STEP_PID INTEGER,
		PARAM_LIST_KEY SMALLINT,
		PARAM_SET_KEY SMALLINT,
		PARAM_NAME_KEY SMALLINT,
		VALUE_IS_DATA_ALIAS BOOLEAN,
		VALUE_IS_OTHER_ALIAS BOOLEAN,
		ALIAS_KEY SMALLINT,
		DEFLT_PARAM_STEP_PID INTEGER,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE CONTAIN_NAME_MAPS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		CONTAIN_NAME_MAP_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_NAME_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		ELEMENT_TYPE_KEY SMALLINT,
		INFERRED_SHARED INTEGER,
		SHARED INTEGER
	);

CREATE TABLE SENTENCE_STYLE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SENTENCE_STYLE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE CONTAIN_NAME_PARTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		CONTAIN_NAME_PART_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		ELEMENT_TYPE_KEY SMALLINT,
		SHARED INTEGER,
		LANG_CODE VARCHAR(4),
		TRANS VARCHAR(160)
	);

CREATE TABLE PACKAGE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PACKAGE_DEFN_PID INTEGER NOT NULL,
		IS_NATIVE BOOLEAN,
		VERSON_NAME VARCHAR(160),
		PARENT_SCHEMA_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		IS_MAIN_PCKG BOOLEAN,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE LANGUAGE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LANGUAGE_DEFN_PID INTEGER NOT NULL,
		LANGUAGE_CODE VARCHAR(4),
		LANGUAGE_NAME VARCHAR(60),
		IS_GUI_LANG BOOLEAN,
		IS_DATA_LANG BOOLEAN,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSTN_FILTER_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_FILTER_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		IS_ACTION BOOLEAN,
		IS_JOIN BOOLEAN,
		IS_SORT BOOLEAN,
		SCRIPT_GROUP_KEY SMALLINT,
		SCRIPT_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE PROJECTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PROJECT_PID INTEGER NOT NULL,
		COMMENCED TIMESTAMP
	);

CREATE TABLE SUBSET_SINGLE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSET_SINGLE_DEFN_PID INTEGER NOT NULL,
		SUBSET_PID INTEGER,
		USE_ORDER INTEGER,
		REFER_PID INTEGER,
		COUNT INTEGER
	);

CREATE TABLE OCCASN_BTWN_ASSOCS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		OCCASN_BTWN_ASSOC_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		OCCASN_BTWN_ASSOC_TAG_KEY SMALLINT,
		OCCASN_SUB_TYPE_KEY SMALLINT,
		THIS_OCCASN_PID INTEGER,
		A_ENTITY_TYPE_KEY SMALLINT,
		A_ENTITY_SUB_TYPE_KEY SMALLINT,
		A_ENTITY_PID INTEGER,
		B_ENTITY_TYPE_KEY SMALLINT,
		B_ENTITY_SUB_TYPE_KEY SMALLINT,
		B_ENTITY_PID INTEGER,
		THEME_KEY SMALLINT,
		SENTCE_STYLE_KEY SMALLINT,
		A_B_SENTCE_SET_PID INTEGER,
		B_A_SENTCE_SET_PID INTEGER,
		MEMO_SET_PID INTEGER,
		FLAGS VARBINARY(100)
	);

CREATE TABLE SUBSET_BIO_NETWORK_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSET_BIO_NETWORK_DEFN_PID INTEGER NOT NULL,
		SUBSET_PID INTEGER,
		USE_ORDER INTEGER,
		BIO_PID INTEGER,
		PARENT_SET_PID INTEGER,
		THIS_GENERATION SMALLINT,
		MIN_GENERATION SMALLINT,
		IS_ANCESTRAL_LINK BOOLEAN,
		IS_VIA_FEMALE_ANCESTOR BOOLEAN,
		KIN_CODE SMALLINT,
		COMMON_PARENT_SET_PID INTEGER
	);

CREATE TABLE MESSAGE_TEMPLATE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		MESSAGE_TEMPLATE_DEFN_PID INTEGER NOT NULL,
		PLUGIN_KEY SMALLINT,
		REQUESTER_TYPE_KEY SMALLINT,
		REQUESTER_SUB_TYPE_KEY SMALLINT,
		REQUESTER_PID INTEGER,
		SITE_KEY SMALLINT,
		IS_ERROR BOOLEAN
	);

CREATE TABLE OCCASN_NOTEPADS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEYD SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		OCCASN_NOTEPAD_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		NOTEPAD_DEFN_PID SMALLINT,
		NOTEPAD VARCHAR(32000)
	);

CREATE TABLE SUBSTN_PARAM_LISTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_PARAM_LIST_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARAM_SET_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSTN_PARAM_SET_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_PARAM_SET_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		VIEW_DATA_SCRIPT_GROUP_KEY SMALLINT,
		VIEW_DATA_SCRIPT_PID INTEGER,
		MODIFY_DATA_SCRIPT_GROUP_KEY SMALLINT,
		MODIFY_DATA_SCRIPT_PID INTEGER,
		DELETE_DATA_SCRIPT_GROUP_KEY SMALLINT,
		DELETE_DATA_SCRIPT_PID INTEGER,
		EVAL_DATA_SCRIPT_GROUP_KEY SMALLINT,
		EVAL_DATA_SCRIPT_PID INTEGER,
		PARAM_SET_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSET_MIX_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSET_MIX_DEFN_PID INTEGER NOT NULL,
		SUBSET_PID INTEGER,
		USE_ORDER INTEGER,
		REFER1_PID INTEGER,
		REFER2_PID INTEGER
	);

CREATE TABLE DIGITAL_NAME_MAPS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		DIGITAL_NAME_MAP_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_NAME_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		ELEMENT_TYPE_KEY INTEGER,
		SHARED INTEGER,
		INFERRED_SHARED INTEGER
	);

CREATE TABLE FIELD_DATA_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FIELD_DATA_TYPE_DEFN_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSTN_TEMPLATE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_TEMPLATE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		IS_TEXT_LAYOUT BOOLEAN,
		IS_TEXT_STYLE BOOLEAN,
		SCRIPT_GROUP_KEY SMALLINT,
		SCRIPT_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE OCCASN_NAME_PARTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		OCCASN_NAME_PART_PID INTEGER NOT NULL,
		ELEMENT_PID SMALLINT,
		THIS_NAME_EVENT_PID INTEGER,
		NEXT_NAME_EVENT_PID INTEGER,
		SHARED INTEGER,
		LANG_CODE VARCHAR(4),
		TRANS VARCHAR(160)
	);

CREATE TABLE LIST_SORTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LIST_SORT_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_SORT_SET_KEY SMALLINT,
		USE_ORDER SMALLINT,
		SORT_ALIAS VARCHAR(300),
		SORT_HIGH_LAST BOOLEAN,
		EMPTY_SORT_HIGH BOOLEAN
	);

CREATE TABLE FIELD_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FIELD_TYPE_DEFN_PID INTEGER NOT NULL,
		DATA_TYPE_PID SMALLINT,
		IN_FORMAT_PID INTEGER,
		OUT_FORMAT_KEY SMALLINT,
		MIN_INTEGER BIGINT,
		MAX_INTEGER BIGINT,
		MIN_FLOAT DOUBLE,
		MAX_FLOAT DOUBLE,
		MAX_STRING_LEN INTEGER,
		MIN_STRING_LEN INTEGER,
		ENCODING_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE FLAG_STATE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FLAG_STATE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_TYPE_KEY SMALLINT,
		PARENT_SUB_TYPE_KEY SMALLINT,
		PARENT_FLAG_SLOT SMALLINT,
		STATE_VALUE SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSTN_COMMONS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_COMMON_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		SUBSTN_TYPE_KEY SMALLINT,
		PARENT_STEP_PID INTEGER,
		SCRIPT_GROUP_KEY SMALLINT,
		SCRIPT_KEY SMALLINT,
		PARAMS_SET_KEY SMALLINT,
		THIS_PARAMS_KEY SMALLINT,
		DEFLT_PARAMS_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE OCCASN_NAME_MAPS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		OCCASN_NAME_MAP_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_NAME_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		ELEMENT_TYPE_KEY SMALLINT,
		SHARED INTEGER,
		INFERRED_SHARED INTEGER
	);

CREATE TABLE CITATIONS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		CITATION_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		CITN_TYPE_KEY SMALLINT,
		CITING_PID INTEGER,
		SOURCE_SUB_TYPE_KEY SMALLINT,
		SOURCE_PID INTEGER,
		MEMO_SET_PID INTEGER,
		SURETY VARCHAR(10),
		FLAGS VARCHAR(50)
	);

CREATE TABLE RECORD_VALID_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		RECORD_VALID_DEFN_PID INTEGER NOT NULL,
		VIEW_SCRIPT_GROUP_KEY SMALLINT,
		VIEW_SCRIPT_PID INTEGER,
		MODIFY_SCRIPT_GROUP_KEY SMALLINT,
		MODIFY_SCRIPT_PID INTEGER,
		DELETE_SCRIPT_GROUP_KEY SMALLINT,
		DELETE_SCRIPT_PID INTEGER,
		REMINDER SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE NAME_STYLE_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NAME_STYLE_TYPE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		ENTITY_TYPE_KEY SMALLINT,
		ENTITY_SUB_TYPE_KEY SMALLINT,
		START_USAGE_PID INTEGER,
		END_USAGE_PID INTEGER,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE USER_GROUP_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		USER_GROUP_DEFN_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SCRIPT_GROUP_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SCRIPT_GROUP_DEFN_PID INTEGER NOT NULL,
		ACTION_TYPE_KEY SMALLINT,
		INPUT_FOCUS_TYPE_KEY SMALLINT,
		INPUT_SUB_TYPE_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE GUI_LANGUAGE_NAMES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		GUI_LANGUAGE_NAME_PID INTEGER NOT NULL,
		FROM_LANGUAGE VARCHAR(4),
		TO_LANGUAGE VARCHAR(4),
		TRANSLATION VARCHAR(60)
	);

CREATE TABLE HINTERVAL_INTERVAL_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		HINTERVAL_INTERVAL_TYPE_DEFN_PID INTEGER NOT NULL,
		ORIGINAL_CALENDAR_KEY SMALLINT,
		WHEN_WRITTEN SMALLINT,
		WHERE_WRITTEN_PID INTEGER,
		CAL_CHNG_START_YEAR SMALLINT,
		CAL_CHNG_START_DAY SMALLINT,
		CAL_CHNG_END_YEAR SMALLINT,
		CAL_CHNG_END_DAY SMALLINT,
		DAYS_LOST SMALLINT,
		USED_OLD_STYLE BOOLEAN,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE DIGITAL_NOTEPADS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		DIGITAL_NOTEPAD_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		NOTEPAD_DEFN_PID SMALLINT,
		NOTEPAD VARCHAR(32000)
	);

CREATE TABLE SUBSTN_DATA_ALIASES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_DATA_ALIAS_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		IS_COMPLETE BOOLEAN,
		IS_HEAD_ONLY BOOLEAN,
		IS_HEAD_LINK_ONLY BOOLEAN,
		IS_LINK_ONLY BOOLEAN,
		IS_LINK_OUTPUT_ONLY BOOLEAN,
		IS_OUTPUT_ONLY BOOLEAN,
		TOP_STEP_KEY SMALLINT,
		REQUESTER_TYPE_KEY SMALLINT,
		REQUESTER_SUB_TYPE_KEY SMALLINT,
		OUTPUT_TYPE_KEY SMALLINT,
		OUTPUT_SUB_TYPE_KEY SMALLINT,
		PARAM_LIST_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE PHYSICAL_NAME_PARTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PHYSICAL_NAME_PART_PID INTEGER NOT NULL,
		ELEMENT_PID SMALLINT,
		THIS_NAME_EVENT_PID INTEGER,
		NEXT_NAME_EVENT_PID INTEGER,
		SHARED INTEGER,
		LANG_CODE VARCHAR(4),
		TRANS VARCHAR(160)
	);

CREATE TABLE LABEL_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LABEL_TRAN_PID INTEGER NOT NULL,
		IS_USER_DATA BOOLEAN,
		TABLE_KEY SMALLINT,
		FIELD_KEY SMALLINT,
		RECORD_PID INTEGER,
		SORT_ORDER SMALLINT,
		LANG_CODE VARCHAR(4),
		ABBREV VARCHAR(60),
		NAME VARCHAR(160),
		DESCRIPTION VARCHAR(300),
		STEP_PID INTEGER
	);

CREATE TABLE LIST_SORT_SETS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LIST_SORT_SET_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		INPUT_TYPE_KEY SMALLINT,
		INPUT_SUB_TYPE_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE COMMIT_ITEMS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		COMMIT_ITEM_PID INTEGER NOT NULL,
		PARENT_CMT_PID INTEGER,
		TABLE_KEY SMALLINT,
		RECORD_PID INTEGER,
		PREV_CMT_PID INTEGER
	);

CREATE TABLE PHYSICAL_NAMES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PHYSICAL_NAME_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		NAME_TAG_KEY SMALLINT,
		NAME_STYLE_KEY SMALLINT,
		ELEMENTS_ENTERED VARBINARY(8),
		THIS_HDATE_PID INTEGER,
		THIS_NAME_EVENT_PID INTEGER,
		THIS_HDATE_INFERRED BOOLEAN,
		NEXT_HDATE_PID INTEGER,
		NEXT_NAME_EVENT_PID INTEGER,
		NEXT_HDATE_INFERRED BOOLEAN,
		THEME_KEY SMALLINT,
		SENTCE_SET_KEY INTEGER,
		SENTCE_TYPE_KEY SMALLINT,
		SENTCE_STYLE_KEY SMALLINT,
		MEMO_SET_PID INTEGER
	);

CREATE TABLE FIELD_RECENTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FIELD_RECENT_PID INTEGER NOT NULL,
		TABLE_KEY SMALLINT,
		FIELD_PID SMALLINT,
		RECENT01_PID INTEGER,
		RECENT02_PID INTEGER,
		RECENT03_PID INTEGER,
		RECENT04_PID INTEGER,
		RECENT05_PID INTEGER,
		RECENT06_PID INTEGER,
		RECENT07_PID INTEGER,
		RECENT08_PID INTEGER,
		RECENT09_PID INTEGER,
		RECENT10_PID INTEGER,
		RECENT11_PID INTEGER,
		RECENT12_PID INTEGER,
		RECENT13_PID INTEGER,
		RECENT14_PID INTEGER,
		RECENT15_PID INTEGER,
		FIXED01_PID INTEGER,
		FIXED02_PID INTEGER,
		FIXED03_PID INTEGER,
		FIXED04_PID INTEGER,
		FIXED05_PID INTEGER
	);

CREATE TABLE DISPLAY_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		DISPLAY_TYPE_DEFN_PID INTEGER NOT NULL,
		SCREEN_COUNT SMALLINT,
		WIDTH INTEGER,
		HEIGHT INTEGER,
		HAS_KEYBOARD BOOLEAN,
		TOUCH_SCREEN BOOLEAN,
		AUTO_ROTATE BOOLEAN,
		HAS_INTERNET BOOLEAN,
		HAS_SERVER BOOLEAN,
		REMINDER SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE BIOS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		BIO_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		VISIBLE_ID INTEGER NOT NULL,
		SUB_TYPE_KEY SMALLINT,
		BEST_NAME_PID INTEGER,
		BEST_BIRTH_PID INTEGER,
		BEST_DEATH_PID INTEGER,
		BEST_BIO_MALE_PARENT_PID INTEGER,
		BEST_BIO_FEMALE_PARENT_PID INTEGER,
		USE_BIO_MALE_PARENT BOOLEAN,
		USE_BIO_FEMALE_PARENT BOOLEAN,
		BEST_NON_BIO_PARENT1_PID INTEGER,
		BEST_NON_BIO_PARENT2_PID INTEGER,
		BEST_IMAGE_PID INTEGER,
		SEX_KEY SMALLINT,
		LIVING_KEY SMALLINT,
		SPERM_PROVIDER_ISSUE_ORDER SMALLINT,
		EGG_PROVIDER_ISSUE_ORDER SMALLINT,
		SURETY VARCHAR(10),
		FLAGS VARBINARY(100)
	);

CREATE TABLE LIVING_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LIVING_DEFN_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE TEXT_STYLE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		TEXT_STYLE_DEFN_PID INTEGER NOT NULL,
		IS_USER_DEFN BOOLEAN,
		FONT_NAME VARCHAR(60),
		FONT_SIZE SMALLINT,
		FONT_IS_BOLD BOOLEAN,
		FONT_IS_ITALIC BOOLEAN,
		FONT_UNDERLINED BOOLEAN,
		FONT_COLOR SMALLINT,
		HIGHLIGHT_COLOR SMALLINT,
		TEXT_LINK_KEY SMALLINT,
		MARKER1_LINK_KEY SMALLINT,
		MARKER2_LINK_KEY SMALLINT,
		MARKER3_LINK_KEY SMALLINT,
		MARKER4_LINK_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE OCCASN_ASSOCS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER,
		OCCASN_ASSOC_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		OCCASN_ASSOC_TAG_KEY SMALLINT,
		OCCASN_SUB_TYPE_KEY SMALLINT,
		OCCASN_PID INTEGER,
		ASSOC_TYPE_KEY SMALLINT,
		ASSOC_SUB_TYPE_KEY SMALLINT,
		ASSOC_TYPE_PID INTEGER,
		ASSOC_NAME_USED_PID INTEGER,
		THEME_KEY INTEGER,
		LOCAL_SENTCE_SET_PID INTEGER,
		SENTCE_STYLE_KEY SMALLINT,
		MEMO_SET_PID INTEGER,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE PUBLISH_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PUBLISH_TYPE_DEFN_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE USER_MESSAGES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		USER_MESSAGE_PID INTEGER NOT NULL,
		FROM_USER_PID INTEGER,
		TO_USER_PID INTEGER,
		TIME_SENT TIMESTAMP,
		MESSAGE VARCHAR(300),
		IS_READ BOOLEAN,
		IS_ACKD BOOLEAN,
		REPLIED BOOLEAN
	);

CREATE TABLE HINTERVALS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER,
		HINTERVAL_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		IS_HUMAN_CALENDAR BOOLEAN,
		HINTERVAL1 BIGINT,
		HINTERVAL2 BIGINT,
		SORT_HINTERVAL1 BIGINT,
		SORT_HINTERVAL2 BIGINT,
		ORIGINAL_TEXT VARCHAR(160),
		LANG_CODE VARCHAR(4),
		HINTERVAL_TYPE_KEY SMALLINT,
		NAMED_MEMO_PID INTEGER,
		SURETY VARCHAR(10)
	);

CREATE TABLE NOTEPAD_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NOTEPAD_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_TYPE_KEY SMALLINT,
		PARENT_SUB_TYPE_KEY SMALLINT,
		LENGTH SMALLINT,
		UNITS_KEY SMALLINT,
		NOTEPAD_STORAGE_KEY SMALLINT,
		FIELD_TYPE_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSET_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSET_TYPE_DEFN_PID INTEGER NOT NULL,
		FOCUS1_TYPE_KEY SMALLINT,
		FOCUS1_SUB_TYPE_KEY SMALLINT,
		IS_ALL BOOLEAN,
		IS_SINGLE BOOLEAN,
		FOCUS2_TYPE_KEY SMALLINT,
		FOCUS2_SUB_TYPE_KEY SMALLINT,
		IS_MIXED BOOLEAN,
		IS_BIO_NETWORK BOOLEAN,
		BIO_FOCUS_PID INTEGER,
		ANCESTOR_GENS SMALLINT,
		DESCENDANT_GENS SMALLINT,
		EXCLUDE_NON_GENETIC_LINKS BOOLEAN,
		EXCLUDE_MIXED_SEX_LINKS BOOLEAN,
		USE_BIO_FLAG INTEGER,
		BIO_FLAG_STATE SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE NAME_ELMNT_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NAME_ELMNT_TYPE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		DATA_TYPE_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE LIST_OBJECTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LIST_OBJECT_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_OBJ_SET_KEY SMALLINT,
		USE_ORDER SMALLINT,
		OBJECT_ALIAS VARCHAR(300),
		USE_ALIAS_LABEL BOOLEAN,
		MARGIN_LABEL VARCHAR(100),
		LABEL_STYLE_KEY SMALLINT,
		CELL_STYLE_KEY SMALLINT,
		CELL_MIN_WIDTH SMALLINT,
		CELL_MIN_HEIGHT SMALLINT,
		CELL_NOW_WIDTH SMALLINT,
		CELL_NOW_HEIGHT SMALLINT,
		ACCENT_KEY SMALLINT,
		ACCENT_ALIAS VARCHAR(300)
	);

CREATE TABLE HDATE_MODIFIER_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		HDATE_MODIFIER_DEFN_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE COMMIT_LOGS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		COMMIT_LOG_PID INTEGER NOT NULL,
		COMMENCED TIMESTAMP,
		COMPLETED TIMESTAMP,
		USER_PID INTEGER,
		CLIENT_PID INTEGER,
		NUM_TABLES SMALLINT
	);

CREATE TABLE TABLE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		TABLE_DEFN_PID INTEGER NOT NULL,
		PLUGIN_KEY SMALLINT,
		LAST_RECORD_PID INTEGER,
		VERSION_NAME VARCHAR(160),
		SQL_NAME VARCHAR(30),
		STORAGE_TYPE_KEY SMALLINT,
		RECORD_VALID_KEY SMALLINT,
		HAS_FLAGS BOOLEAN,
		HAS_NOTEPADS BOOLEAN
	);

CREATE TABLE SUBSTN_SYNTAX_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_SYNTAX_DEFN_PID INTEGER NOT NULL,
		ENCLOSES_MARKUP BOOLEAN,
		INTERNAL_BEGIN_MARK VARCHAR(10),
		VISIBLE_BEGIN_MARK VARCHAR(10),
		INTERNAL_END_MARK VARCHAR(10),
		VISIBLE_END_MARK VARCHAR(10),
		INTERNAL_BEGIN_TRUE VARCHAR(10),
		VISIBLE_BEGIN_TRUE VARCHAR(10),
		INTERNAL_END_TRUE VARCHAR(10),
		VISIBLE_END_TRUE VARCHAR(10),
		INTERNAL_DIVIDER_MARK VARCHAR(10),
		VISIBLE_DIVIDER_MARK VARCHAR(10),
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE CONTAIN_NOTEPADS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		CONTAIN_NOTEPAD_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		NOTEPAD_DEFN_KEY SMALLINT,
		NOTEPAD VARCHAR(32000)
	);

CREATE TABLE BIO_NOTEPADS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER,
		BIO_NOTEPAD_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		NOTEPAD_DEFN_KEY SMALLINT,
		NOTEPAD VARCHAR(32000)
	);

CREATE TABLE HDATE_CALENDAR_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		HDATE_CALENDAR_DEFN_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE CONTAIN_NAMES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		CONTAIN_NAME_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		NAME_TAG_KEY SMALLINT,
		NAME_STYLE_KEY SMALLINT,
		ELEMENTS_ENTERED VARBINARY(8),
		THIS_HDATE_PID INTEGER,
		THIS_NAME_EVENT_PID INTEGER,
		THIS_HDATE_INFERRED BOOLEAN,
		NEXT_HDATE_PID INTEGER,
		NEXT_NAME_EVENT_PID INTEGER,
		NEXT_HDATE_INFERRED BOOLEAN,
		THEME_KEY SMALLINT,
		SENTCE_SET_PID INTEGER,
		SENTCE_TYPE_KEY SMALLINT,
		SENTCE_STYLE_KEY SMALLINT,
		MEMO_SET_PID INTEGER
	);

CREATE TABLE LANGUAGE_USES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LANGUAGE_USE_PID INTEGER NOT NULL,
		GUI_LANGUAGE VARCHAR(4),
		DATA1_LANGUAGE VARCHAR(4),
		DATA2_LANGUAGE VARCHAR(4),
		REPORT_LANGUAGE VARCHAR(4),
		DFLT_LANGUAGE VARCHAR(4)
	);

CREATE TABLE CONTAINS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		CONTAIN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		VISIBLE_ID INTEGER,
		SUB_TYPE_KEY SMALLINT,
		BEST_NAME_PID INTEGER,
		BEST_CREATE_PID INTEGER,
		BEST_DESTROY_PID INTEGER,
		BEST_IMAGE_PID INTEGER,
		SURETY VARCHAR(10),
		FLAGS VARBINARY(100)
	);

CREATE TABLE OCCASN_NAMES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		OCCASN_NAME_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_PID INTEGER,
		PARENT_SUB_TYPE_KEY SMALLINT,
		NAME_TAG_KEY SMALLINT,
		NAME_STYLE_KEY SMALLINT,
		ELEMENTS_ENTERED VARBINARY(8),
		THIS_HDATE_PID INTEGER,
		THIS_NAME_EVENT_PID INTEGER,
		THIS_HDATE_INFERRED BOOLEAN,
		NEXT_HDATE_PID INTEGER,
		NEXT_NAME_EVENT_PID INTEGER,
		NEXT_HDATE_INFERRED BOOLEAN,
		THEME_KEY SMALLINT,
		SENTCE_SET_KEY INTEGER,
		SENTCE_TYPE_KEY SMALLINT,
		SENTCE_STYLE_KEY SMALLINT,
		MEMO_SET_PID INTEGER
	);

CREATE TABLE OCCASN_TAG_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER,
		OCCASN_TAG_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		VIEW_DATA_SCRIPT_GROUP_KEY SMALLINT,
		VIEW_DATA_SCRIPT_PID INTEGER,
		MODIFY_DATA_SCRIPT_GROUP_KEY SMALLINT,
		MODIFY_DATA_SCRIPT_PID INTEGER,
		DELETE_DATA_SCRIPT_GROUP_KEY SMALLINT,
		DELETE_DATA_SCRIPT_PID INTEGER,
		IS_EVENT BOOLEAN,
		MIN_NUM_LOCATION_ASSOC SMALLINT,
		HAS_PARENTS BOOLEAN,
		MAX_NUM_LOCATION_ASSOC SMALLINT,
		MIN_NUM_HDATE_ASSOC SMALLINT,
		MAX_NUM_HDATE_ASSOC SMALLINT,
		MIN_NUM_KEY_ASSOC SMALLINT,
		MAX_NUM_KEY_ASSOC SMALLINT,
		DFLT_TAG_GROUP_KEY SMALLINT,
		DFLT_THEME_KEY SMALLINT,
		SENTCE_SET_TYPE_KEY SMALLINT,
		SENTCE_STYLE_TYPE_KEY SMALLINT,
		GLOBAL_SENTCE_SET_KEY SMALLINT,
		MEMO_SET_TYPE_KEY SMALLINT,
		GEDCOM_TAG VARCHAR(30),
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE PHYSICALS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		PHYSICAL_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		VISIBLE_ID INTEGER,
		SUB_TYPE_KEY SMALLINT,
		BEST_NAME_PID INTEGER,
		BEST_CREATE_PID INTEGER,
		BEST_DESTROY_PID INTEGER,
		BEST_IMAGE_PID INTEGER,
		SURETY VARCHAR(10),
		FLAGS VARBINARY(100)
	);

CREATE TABLE NAME_TEMPLATE_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_PID SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		NAME_TEMPLATE_TYPE_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		ENTITY_TYPE_KEY SMALLINT,
		ENTITY_SUB_TYPE_KEY SMALLINT,
		SORTING_ONLY BOOLEAN,
		IS_MANDATORY BOOLEAN,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE FIELD_FORMAT_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		FIELD_FORMAT_DEFN_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE BIO_NAME_PARTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER,
		BIO_NAME_PART_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		ELEMENT_PID INTEGER,
		THIS_NAME_EVENT_PID INTEGER,
		NEXT_NAME_EVENT_PID INTEGER,
		SHARED INTEGER,
		LANG_CODE VARCHAR(4),
		TRANS VARCHAR(160)
	);

CREATE TABLE DIGITAL_NAME_PARTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		DIGITAL_NAME_PART_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		ELEMENT_TYPE_KEY SMALLINT,
		SHARED INTEGER,
		LANG_CODE VARCHAR(4),
		TRANS VARCHAR(160)
	);

CREATE TABLE OCCASN_TIMELINE_ELMNTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER,
		OCCASN_TIMELINE_ELMNT_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		TIMELINE_PID SMALLINT,
		OCCASN_PID INTEGER,
		SUB_TYPE_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE VIEWPOINT_CONFIGS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		VIEWPOINT_CONFIG_PID INTEGER NOT NULL,
		VIEWPOINT_TYPE_KEY SMALLINT,
		VIEWPOINT_SUB_TYPE_KEY SMALLINT,
		DISPLAY_TYPE_KEY SMALLINT,
		LEFT_EDGE INTEGER,
		TOP_EDGE INTEGER,
		WIDTH INTEGER,
		HEIGHT INTEGER,
		LAST_OPENED TIMESTAMP,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE HINTERVAL_MODIFIER_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		HINTERVAL_MODIFIER_DEFN_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE TAG_GROUP_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		TAG_GROUP_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PLUGIN_KEY SMALLINT,
		ENTITY_TYPE_KEY SMALLINT,
		ENTITY_SUB_TYPE_KEY SMALLINT,
		IS_MAJOR_GROUP BOOLEAN,
		MAJOR_GRP_KEY SMALLINT,
		MINOR_GRP_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SENTENCE_SET_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SENTENCE_SET_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		PARENT_TAG_TYPE_KEY SMALLINT,
		PARENT_TAG_PID SMALLINT,
		SENTCE_STYLE_TYPE_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE GUI_ELEMENTS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		GUI_ELEMENT_PID INTEGER NOT NULL,
		PLUGIN_KEY SMALLINT,
		GUI_SCREEN_PID SMALLINT
	);

CREATE TABLE USER_GROUP_RIGHTS_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		USER_GROUP_RIGHTS_DEFN_PID INTEGER NOT NULL,
		USER_GROUP_KEY SMALLINT,
		TABLE_KEY SMALLINT,
		CAN_VIEW_ALL BOOLEAN,
		CAN_VIEW_SOME BOOLEAN,
		CAN_EDIT_VIEW BOOLEAN,
		CAN_DELETE_EDITABLE BOOLEAN,
		LIMIT_FLAG_KEY SMALLINT,
		LIMIT_FLAG_VALUE SMALLINT,
		REMINDER_KEY SMALLINT
	);

CREATE TABLE HDATE_DATE_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		HDATE_DATE_TYPE_DEFN_PID INTEGER NOT NULL,
		ORIGINAL_CALENDAR_KEY SMALLINT,
		WHEN_WRITTEN SMALLINT,
		WHERE_WRITTEN_PID INTEGER,
		CAL_CHNG_START_YEAR SMALLINT,
		CAL_CHNG_START_DAY SMALLINT,
		CAL_CHNG_END_YEAR SMALLINT,
		CAL_CHNG_END_DAY SMALLINT,
		DAYS_LOST SMALLINT,
		USED_OLD_STYLE BOOLEAN,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE LIFE_PHASE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		LIFE_PHASE_DEFN_PID INTEGER NOT NULL,
		PLUGIN_KEY SMALLINT,
		ENTITY_TYPE_KEY SMALLINT,
		ENTITY_SUB_TYPE_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE REMINDER_TRANS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		REMINDER_TRAN_PID INTEGER NOT NULL,
		PLUGIN_KEY SMALLINT,
		IS_WHOLE_SCREEN BOOLEAN,
		SCREEN_KEY SMALLINT,
		SCREEN_PID SMALLINT,
		ENTITY_TYPE_KEY SMALLINT,
		SUB_TYPE_KEY SMALLINT,
		LANG_CODE VARCHAR(4),
		ENCODING_KEY SMALLINT,
		REMINDER VARCHAR(400)
	);

CREATE TABLE SUBSTN_TEMPLATES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_TEMPLATE_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		LAYOUT_STYLE_CLASS_KEY SMALLINT,
		PARENT_STEP_PID INTEGER,
		SCRIPT_GROUP_KEY SMALLINT,
		SCRIPT_KEY SMALLINT,
		PARAMS_SET_KEY SMALLINT,
		THIS_PARAMS_KEY SMALLINT,
		DEFLT_PARAMS_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSTN_COMMON_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_COMMON_DEFN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		IS_DATA_RETRIEVAL BOOLEAN,
		IS_VALUE_COMPARE BOOLEAN,
		TOP_STEP_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE SCRIPT_ACTION_TYPE_DEFNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SCRIPT_ACTION_TYPE_DEFN_PID INTEGER NOT NULL,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		IS_DEFAULT BOOLEAN,
		SHOW BOOLEAN
	);

CREATE TABLE SUBSTN_OTHER_ALIASES (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_OTHER_ALIAS_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		IS_TEXT_LAYOUT_RELATED BOOLEAN,
		IS_TEXT_STYLE_RELATED BOOLEAN,
		TOP_STEP_KEY SMALLINT,
		REQUESTER_TYPE_KEY SMALLINT,
		REQUESTER_SUB_TYPE_KEY SMALLINT,
		OUTPUT_TYPE_KEY SMALLINT,
		OUTPUT_SUB_TYPE_KEY SMALLINT,
		PARAM_LIST_KEY SMALLINT,
		REMINDER_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE TABLE OCCASN_OCCASNS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		OCCASN_OCCASN_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		OCCASN_OCCASN_TAG_KEY SMALLINT,
		A_OCCASN_SUB_TYPE_KEY SMALLINT,
		A_OCCASN_PID INTEGER,
		B_OCCASN_SUB_TYPE_KEY SMALLINT,
		B_OCCASN_PID INTEGER,
		THEME_KEY SMALLINT,
		SENTCE_STYLE_KEY SMALLINT,
		A_B_SENTCE_SET_PID INTEGER,
		B_A_SENTCE_SET_PID INTEGER,
		MEMO_SET_PID INTEGER,
		DISPLAY_ORDER SMALLINT,
		FLAGS VARBINARY(10)
	);

CREATE TABLE BIO_PARENT_SETS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		BIO_PARENT_SET_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		VISIBLE_ID INTEGER,
		BIO_SUB_TYPE_KEY SMALLINT,
		OCCASN_SUB_TYPE_KEY SMALLINT,
		OCCASN_PID INTEGER,
		SPERM_PROVIDER_PID INTEGER,
		EGG_PROVIDER_PID INTEGER,
		MITO_PROVIDER_PID INTEGER,
		UTERUS_PROVIDER_PID INTEGER,
		SOCIAL_PARENT1_PID INTEGER,
		SOCIAL_PARENT2_PID INTEGER
	);

CREATE TABLE SUBSTN_FILTERS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		SUBSTN_FILTER_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		SUBSTN_TYPE_KEY SMALLINT,
		PARENT_STEP_PID INTEGER,
		SCRIPT_GROUP_KEY SMALLINT,
		SCRIPT_KEY SMALLINT,
		PARAMS_SET_KEY SMALLINT,
		THIS_PARAMS_KEY SMALLINT,
		DEFLT_PARAMS_KEY SMALLINT,
		NEXT_SORT_TERM_KEY SMALLINT,
		NEXT_STEP_KEY SMALLINT,
		DISPLAY_ORDER SMALLINT,
		SHOW BOOLEAN
	);

CREATE UNIQUE INDEX PRIMARY_KEY_464 ON SUBSTN_PARAM_SET_DEFNS (SUBSTN_PARAM_SET_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B93 ON LIST_SORT_SETS (LIST_SORT_SET_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B9 ON LANGUAGE_DEFNS (LANGUAGE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_60 ON OCCASN_OCCASN_TAG_DEFNS (OCCASN_OCCASN_TAG_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_56 ON NAME_TEMPLATE_TYPE_DEFNS (NAME_TEMPLATE_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_3 ON BIO_ETHNICITY_DEFNS (BIO_ETHNICITY_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_CD ON CONTAINS (CONTAIN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_5 ON BIO_KIN_TERM_DEFNS (BIO_KIN_TERM_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_84 ON OCCASN_TIMELINE_ELMNTS (OCCASN_TIMELINE_ELMNT_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_5F ON BIO_KIN_TERM_TRANS (BIO_KIN_TERM_TRAN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_46 ON SUBSTN_FILTER_DEFNS (SUBSTN_FILTER_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_24 ON FIELD_FORMAT_DEFNS (FIELD_FORMAT_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_2C ON GUI_SCREEN_CONFIGS (GUI_SCREEN_CONFIG_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_3E ON FIELD_VALID_DEFNS (FIELD_VALID_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_85 ON UNITS_DEFNS (UNITS_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_62 ON OCCASN_ASSOC_TAG_DEFNS (OCCASN_ASSOC_TAG_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6D0 ON SUBSTN_PARAM_NAMES (SUBSTN_PARAM_NAME_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_FC ON SUBSET_DEFNS (SUBSET_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_29C ON USER_MESSAGES (USER_MESSAGE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B13 ON SUBSTN_TEMPLATE_DEFNS (SUBSTN_TEMPLATE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1F ON BIOS (BIO_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F3 ON OCCASN_NAME_PARTS (OCCASN_NAME_PART_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F85 ON SUBSET_SINGLE_DEFNS (SUBSET_SINGLE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_7F ON OCCASN_NOTEPADS (OCCASN_NOTEPAD_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8 ON FLAG_DEFNS (FLAG_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_45 ON SUBSTN_OTHER_ALIASES (SUBSTN_OTHER_ALIAS_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_2 ON DIGITALS (DIGITAL_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_4C ON SCRIPT_ACTION_TYPE_DEFNS (SCRIPT_ACTION_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_D9 ON ROLE_NAME_TRANS (ROLE_NAME_TRAN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_2B ON HDATE_CALENDAR_DEFNS (HDATE_CALENDAR_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_21 ON USER_GROUP_DEFNS (USER_GROUP_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_CF ON LABEL_TRANS (LABEL_TRAN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_DC1 ON ROLE_PAIR_NAME_TRANS (ROLE_PAIR_NAME_TRAN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_77 ON MESSAGE_TEMPLATE_DEFNS (MESSAGE_TEMPLATE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_D6 ON SUBSTN_STEPS (SUBSTN_STEP_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_36 ON MEMO_SET_DEFNS (MEMO_SET_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_630 ON SCRIPT_GROUP_DEFNS (SCRIPT_GROUP_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_E76 ON TEMPLATE_TYPE_DEFNS (TEMPLATE_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_78 ON HINTERVALS (HINTERVAL_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_3D ON SUBSTN_SYNTAX_DEFNS (SUBSTN_SYNTAX_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F35 ON SUBSTN_COMMONS (SUBSTN_COMMON_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_2F ON SUBSTN_TEMPLATES (SUBSTN_TEMPLATE_PID ASC);

CREATE INDEX CONSTRAINT_INDEX_1 ON BIOS (BEST_NAME_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1DA ON HDATE_MODIFIER_DEFNS (HDATE_MODIFIER_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_DA ON CITN_TYPE_DEFNS (CITN_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_DA3 ON TABLE_DEFNS (TABLE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_7 ON ENCODING_TYPE_DEFNS (ENCODING_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C0 ON GUI_SCREEN_DEFNS (GUI_SCREEN_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_27 ON NOTEPAD_DEFNS (NOTEPAD_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_4D ON USERS (USER_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C90 ON VIEWPOINT_CONFIGS (VIEWPOINT_CONFIG_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_D0 ON REMINDER_TRANS (REMINDER_TRAN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B7 ON TEXT_STYLE_DEFNS (TEXT_STYLE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A8B ON OCCASN_TAG_DEFNS (OCCASN_TAG_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_44 ON PUBLISH_TYPE_DEFNS (PUBLISH_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_826 ON SESSIONS (SESSION_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1D ON HDATE_DATE_TYPE_DEFNS (HDATE_DATE_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_DC ON COMMIT_LOGS (COMMIT_LOG_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1E ON HINTERVAL_INTERVAL_TYPE_DEFNS (HINTERVAL_INTERVAL_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C ON BIO_PARENT_SETS (BIO_PARENT_SET_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_CE5 ON TAG_GROUP_DEFNS (TAG_GROUP_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_3C ON CITATIONS (CITATION_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F8 ON NAMED_MEMO_TYPE_DEFNS (NAMED_MEMO_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_BF ON SENTENCE_STYLE_DEFNS (SENTENCE_STYLE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_40 ON PHYSICAL_NAME_MAPS (PHYSICAL_NAME_MAP_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_82 ON NAME_OUT_TEMPLATE_DEFNS (NAME_OUT_TEMPLATE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A2 ON LANGUAGE_USES (LANGUAGE_USE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_D8 ON SUBSTN_DATA_ALIASES (SUBSTN_DATA_ALIAS_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_828 ON PHYSICALS (PHYSICAL_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1D3 ON SENTENCE_TYPE_DEFNS (SENTENCE_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_DF ON FIELD_DEFNS (FIELD_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C9 ON OCCASNS (OCCASN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_90 ON ENTITY_NAME_TAG_DEFNS (ENTITY_NAME_TAG_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_EC ON LIST_OBJECTS (LIST_OBJECT_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_74 ON SCHEMA_DEFNS (SCHEMA_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_E ON CONTAIN_NAME_MAPS (CONTAIN_NAME_MAP_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_79 ON ENTITY_SUB_TYPE_DEFNS (ENTITY_SUB_TYPE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C6 ON NAME_STYLE_TYPE_DEFNS (NAME_STYLE_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_E7 ON SEX_DEFNS (SEX_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_3A ON BIO_NAME_MAPS (BIO_NAME_MAP_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_CC ON PHYSICAL_NAME_PARTS (PHYSICAL_NAME_PART_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_7D ON LIST_SORTS (LIST_SORT_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_5BD ON NAME_ELMNT_TYPE_DEFNS (NAME_ELMNT_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_D4 ON SENTENCE_DEFNS (SENTENCE_TEMPLATE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_69 ON RECORD_VALID_DEFNS (RECORD_VALID_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_23 ON HINTERVAL_MODIFIER_DEFNS (HINTERVAL_MODIFIER_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_FE ON LIVING_TYPE_DEFNS (LIVING_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A0 ON NAME_ELMNT_INPUT_DEFNS (NAME_ELMNT_INPUT_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_7A0 ON VIEWPOINT_ELEMENTS (VIEWPOINT_ELEMENT_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_5E ON OCCASN_NAMES (OCCASN_NAME_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_3A1 ON PLUGIN_DEFNS (PLUGIN_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_29 ON SUBSET_MIX_DEFNS (SUBSET_MIX_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_7A ON OCCASN_BTWN_ASSOC_TAG_DEFNS (OCCASN_BTWN_ASSOC_TAG_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6A4 ON OCCASN_ASSOCS (OCCASN_ASSOC_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_67 ON OCCASN_TIMELINE_DEFNS (OCCASN_TIMELINE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_41 ON OCCASN_NAME_MAPS (OCCASN_NAME_MAP_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F31 ON PROJECTS (PROJECT_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_87 ON SUBSTN_FILTERS (SUBSTN_FILTER_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_AC ON THEME_DEFNS (THEME_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_9 ON DIGITAL_NOTEPADS (DIGITAL_NOTEPAD_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_17 ON DIGITAL_NAME_MAPS (DIGITAL_NAME_MAP_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F5 ON LIFE_PHASE_DEFNS (LIFE_PHASE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B2 ON GUI_LANGUAGE_NAMES (GUI_LANGUAGE_NAME_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_94 ON SUBSET_TYPE_DEFNS (SUBSET_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B5B ON SUBSET_PAIR_DEFNS (SUBSET_PAIR_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A8 ON MEMO_DEFNS (MEMO_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_E2 ON DIGITAL_NAMES (DIGITAL_NAME_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A ON COMMIT_ITEMS (COMMIT_ITEM_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_63 ON PACKAGE_DEFNS (PACKAGE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6D ON SUBSET_BIO_NETWORK_DEFNS (SUBSET_BIO_NETWORK_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C7 ON FLAG_STATE_DEFNS (FLAG_STATE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_421 ON SUBSTN_PARAM_VALUES (SUBSTN_PARAM_VALUE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B1 ON DISPLAY_TYPE_DEFNS (DISPLAY_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_75 ON SCRIPT_DEFNS (SCRIPT_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_42 ON OUTPUT_TEMPLATE_TRANS (OUTPUT_TEMPLATE_TRAN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6A ON FIELD_RECENTS (FIELD_RECENT_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_76 ON SCRIPT_TRANS (SCRIPT_TRAN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B1D ON OCCASN_BTWN_ASSOCS (OCCASN_BTWN_ASSOC_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6C ON SUBSTN_PARAM_LISTS (SUBSTN_PARAM_LIST_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_5B7 ON FIELD_TYPE_DEFNS (FIELD_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_50 ON USER_GROUP_RIGHTS_DEFNS (USER_GROUP_RIGHTS_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A7 ON OCCASN_OCCASNS (OCCASN_OCCASN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_2D ON FIELD_DATA_TYPE_DEFNS (FIELD_DATA_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_CE ON PHYSICAL_NAMES (PHYSICAL_NAME_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_4 ON CONTAIN_NOTEPADS (CONTAIN_NOTEPAD_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_D1 ON GUI_LANGUAGES (GUI_LANGUAGE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_25 ON LIST_OBJECT_SETS (LIST_OBJECT_SET_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_5B ON CONTAIN_NAMES (CONTAIN_NAME_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B ON CONTAIN_NAME_PARTS (CONTAIN_NAME_PART_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F ON LANGUAGE_NAME_TRANS (LANGUAGE_NAME_TRAN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_D7 ON DIGITAL_NAME_PARTS (DIGITAL_NAME_PART_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_7E ON HDATES (HDATE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1 ON BIO_NAME_PARTS (BIO_NAME_PART_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B5 ON PHYSICAL_NOTEPADS (PHYSICAL_NOTEPAD_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1C ON SENTENCE_SET_DEFNS (SENTENCE_SET_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6 ON BIO_NOTEPADS (BIO_NOTEPAD_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_242 ON USER_TYPE_DEFNS (USER_TYPE_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_D ON BIO_NAMES (BIO_NAME_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_BC ON SUBSET_FILTER_DEFNS (SUBSET_FILTER_DEFN_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_6E ON GUI_ELEMENTS (GUI_ELEMENT_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8C ON SUBSTN_COMMON_DEFNS (SUBSTN_COMMON_DEFN_PID ASC);

ALTER TABLE LIST_OBJECT_SETS ADD CONSTRAINT CONSTRAINT_25 PRIMARY KEY (LIST_OBJECT_SET_PID);

ALTER TABLE OCCASN_NAMES ADD CONSTRAINT CONSTRAINT_5E PRIMARY KEY (OCCASN_NAME_PID);

ALTER TABLE BIOS ADD CONSTRAINT CONSTRAINT_1F PRIMARY KEY (BIO_PID);

ALTER TABLE FIELD_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_5B7 PRIMARY KEY (FIELD_TYPE_DEFN_PID);

ALTER TABLE SUBSET_PAIR_DEFNS ADD CONSTRAINT CONSTRAINT_B5B PRIMARY KEY (SUBSET_PAIR_PID);

ALTER TABLE ENCODING_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_7 PRIMARY KEY (ENCODING_TYPE_DEFN_PID);

ALTER TABLE GUI_ELEMENTS ADD CONSTRAINT CONSTRAINT_6E PRIMARY KEY (GUI_ELEMENT_PID);

ALTER TABLE SUBSTN_PARAM_SET_DEFNS ADD CONSTRAINT CONSTRAINT_464 PRIMARY KEY (SUBSTN_PARAM_SET_DEFN_PID);

ALTER TABLE SCHEMA_DEFNS ADD CONSTRAINT CONSTRAINT_74 PRIMARY KEY (SCHEMA_DEFN_PID);

ALTER TABLE NAMED_MEMO_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_F8 PRIMARY KEY (NAMED_MEMO_TYPE_DEFN_PID);

ALTER TABLE GUI_SCREEN_CONFIGS ADD CONSTRAINT CONSTRAINT_2C PRIMARY KEY (GUI_SCREEN_CONFIG_PID);

ALTER TABLE LIST_SORT_SETS ADD CONSTRAINT CONSTRAINT_B93 PRIMARY KEY (LIST_SORT_SET_PID);

ALTER TABLE OUTPUT_TEMPLATE_TRANS ADD CONSTRAINT CONSTRAINT_42 PRIMARY KEY (OUTPUT_TEMPLATE_TRAN_PID);

ALTER TABLE SENTENCE_DEFNS ADD CONSTRAINT CONSTRAINT_D4 PRIMARY KEY (SENTENCE_TEMPLATE_DEFN_PID);

ALTER TABLE PUBLISH_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_44 PRIMARY KEY (PUBLISH_TYPE_DEFN_PID);

ALTER TABLE DIGITAL_NAMES ADD CONSTRAINT CONSTRAINT_E2 PRIMARY KEY (DIGITAL_NAME_PID);

ALTER TABLE PLUGIN_DEFNS ADD CONSTRAINT CONSTRAINT_3A1 PRIMARY KEY (PLUGIN_DEFN_PID);

ALTER TABLE PHYSICAL_NOTEPADS ADD CONSTRAINT CONSTRAINT_B5 PRIMARY KEY (PHYSICAL_NOTEPAD_PID);

ALTER TABLE SUBSET_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_94 PRIMARY KEY (SUBSET_TYPE_DEFN_PID);

ALTER TABLE VIEWPOINT_CONFIGS ADD CONSTRAINT CONSTRAINT_C90 PRIMARY KEY (VIEWPOINT_CONFIG_PID);

ALTER TABLE SUBSTN_STEPS ADD CONSTRAINT CONSTRAINT_D6 PRIMARY KEY (SUBSTN_STEP_PID);

ALTER TABLE SUBSET_SINGLE_DEFNS ADD CONSTRAINT CONSTRAINT_F85 PRIMARY KEY (SUBSET_SINGLE_DEFN_PID);

ALTER TABLE BIO_NAMES ADD CONSTRAINT PRIMARY_KEY_D UNIQUE (BIO_NAME_PID);

ALTER TABLE NAME_ELMNT_INPUT_DEFNS ADD CONSTRAINT CONSTRAINT_A0 PRIMARY KEY (NAME_ELMNT_INPUT_DEFN_PID);

ALTER TABLE GUI_LANGUAGE_NAMES ADD CONSTRAINT CONSTRAINT_B2 PRIMARY KEY (GUI_LANGUAGE_NAME_PID);

ALTER TABLE SUBSTN_PARAM_LISTS ADD CONSTRAINT CONSTRAINT_6C PRIMARY KEY (SUBSTN_PARAM_LIST_PID);

ALTER TABLE LANGUAGE_USES ADD CONSTRAINT CONSTRAINT_A2 PRIMARY KEY (LANGUAGE_USE_PID);

ALTER TABLE NAME_OUT_TEMPLATE_DEFNS ADD CONSTRAINT CONSTRAINT_82 PRIMARY KEY (NAME_OUT_TEMPLATE_DEFN_PID);

ALTER TABLE CONTAINS ADD CONSTRAINT CONSTRAINT_CD PRIMARY KEY (CONTAIN_PID);

ALTER TABLE SCRIPT_ACTION_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_4C PRIMARY KEY (SCRIPT_ACTION_TYPE_DEFN_PID);

ALTER TABLE SUBSTN_PARAM_VALUES ADD CONSTRAINT CONSTRAINT_421 PRIMARY KEY (SUBSTN_PARAM_VALUE_PID);

ALTER TABLE GUI_SCREEN_DEFNS ADD CONSTRAINT CONSTRAINT_C0 PRIMARY KEY (GUI_SCREEN_DEFN_PID);

ALTER TABLE ROLE_PAIR_NAME_TRANS ADD CONSTRAINT CONSTRAINT_DC1 PRIMARY KEY (ROLE_PAIR_NAME_TRAN_PID);

ALTER TABLE DIGITAL_NAME_PARTS ADD CONSTRAINT CONSTRAINT_D7 PRIMARY KEY (DIGITAL_NAME_PART_PID);

ALTER TABLE SUBSTN_COMMONS ADD CONSTRAINT CONSTRAINT_F35 PRIMARY KEY (SUBSTN_COMMON_PID);

ALTER TABLE HDATE_MODIFIER_DEFNS ADD CONSTRAINT CONSTRAINT_1DA PRIMARY KEY (HDATE_MODIFIER_DEFN_PID);

ALTER TABLE HINTERVAL_INTERVAL_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_1E PRIMARY KEY (HINTERVAL_INTERVAL_TYPE_DEFN_PID);

ALTER TABLE OCCASN_BTWN_ASSOC_TAG_DEFNS ADD CONSTRAINT CONSTRAINT_7A PRIMARY KEY (OCCASN_BTWN_ASSOC_TAG_DEFN_PID);

ALTER TABLE USER_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_242 PRIMARY KEY (USER_TYPE_DEFN_PID);

ALTER TABLE ENTITY_SUB_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_79 PRIMARY KEY (ENTITY_SUB_TYPE_PID);

ALTER TABLE SCRIPT_TRANS ADD CONSTRAINT CONSTRAINT_76 PRIMARY KEY (SCRIPT_TRAN_PID);

ALTER TABLE CONTAIN_NOTEPADS ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY (CONTAIN_NOTEPAD_PID);

ALTER TABLE LABEL_TRANS ADD CONSTRAINT CONSTRAINT_CF PRIMARY KEY (LABEL_TRAN_PID);

ALTER TABLE FIELD_RECENTS ADD CONSTRAINT CONSTRAINT_6A PRIMARY KEY (FIELD_RECENT_PID);

ALTER TABLE NAME_TEMPLATE_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_56 PRIMARY KEY (NAME_TEMPLATE_TYPE_DEFN_PID);

ALTER TABLE SUBSTN_DATA_ALIASES ADD CONSTRAINT CONSTRAINT_D8 PRIMARY KEY (SUBSTN_DATA_ALIAS_PID);

ALTER TABLE SUBSET_FILTER_DEFNS ADD CONSTRAINT CONSTRAINT_BC PRIMARY KEY (SUBSET_FILTER_DEFN_PID);

ALTER TABLE PHYSICAL_NAME_PARTS ADD CONSTRAINT CONSTRAINT_CC PRIMARY KEY (PHYSICAL_NAME_PART_PID);

ALTER TABLE OCCASN_NAME_MAPS ADD CONSTRAINT CONSTRAINT_41 PRIMARY KEY (OCCASN_NAME_MAP_PID);

ALTER TABLE ENTITY_NAME_TAG_DEFNS ADD CONSTRAINT CONSTRAINT_90 PRIMARY KEY (ENTITY_NAME_TAG_DEFN_PID);

ALTER TABLE OCCASN_ASSOCS ADD CONSTRAINT CONSTRAINT_6A4 PRIMARY KEY (OCCASN_ASSOC_PID);

ALTER TABLE LIST_OBJECTS ADD CONSTRAINT CONSTRAINT_EC PRIMARY KEY (LIST_OBJECT_PID);

ALTER TABLE CONTAIN_NAME_MAPS ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY (CONTAIN_NAME_MAP_PID);

ALTER TABLE SUBSTN_SYNTAX_DEFNS ADD CONSTRAINT CONSTRAINT_3D PRIMARY KEY (SUBSTN_SYNTAX_DEFN_PID);

ALTER TABLE GUI_LANGUAGES ADD CONSTRAINT CONSTRAINT_D1 PRIMARY KEY (GUI_LANGUAGE_PID);

ALTER TABLE LIST_SORTS ADD CONSTRAINT CONSTRAINT_7D PRIMARY KEY (LIST_SORT_PID);

ALTER TABLE SUBSTN_FILTERS ADD CONSTRAINT CONSTRAINT_87 PRIMARY KEY (SUBSTN_FILTER_PID);

ALTER TABLE HDATES ADD CONSTRAINT CONSTRAINT_7E PRIMARY KEY (HDATE_PID);

ALTER TABLE LIVING_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_FE PRIMARY KEY (LIVING_DEFN_PID);

ALTER TABLE PHYSICAL_NAMES ADD CONSTRAINT CONSTRAINT_CE PRIMARY KEY (PHYSICAL_NAME_PID);

ALTER TABLE SCRIPT_DEFNS ADD CONSTRAINT CONSTRAINT_75 PRIMARY KEY (SCRIPT_DEFN_PID);

ALTER TABLE OCCASN_TIMELINE_DEFNS ADD CONSTRAINT CONSTRAINT_67 PRIMARY KEY (OCCASN_TIMELINE_DEFN_PID);

ALTER TABLE UNITS_DEFNS ADD CONSTRAINT CONSTRAINT_85 PRIMARY KEY (UNITS_DEFN_PID);

ALTER TABLE OCCASN_ASSOC_TAG_DEFNS ADD CONSTRAINT CONSTRAINT_62 PRIMARY KEY (OCCASN_ASSOC_TAG_DEFN_PID);

ALTER TABLE MEMO_SET_DEFNS ADD CONSTRAINT CONSTRAINT_36 PRIMARY KEY (MEMO_SET_DEFN_PID);

ALTER TABLE PACKAGE_DEFNS ADD CONSTRAINT CONSTRAINT_63 PRIMARY KEY (PACKAGE_DEFN_PID);

ALTER TABLE HDATE_CALENDAR_DEFNS ADD CONSTRAINT CONSTRAINT_2B PRIMARY KEY (HDATE_CALENDAR_DEFN_PID);

ALTER TABLE LANGUAGE_DEFNS ADD CONSTRAINT CONSTRAINT_B9 PRIMARY KEY (LANGUAGE_DEFN_PID);

ALTER TABLE RECORD_VALID_DEFNS ADD CONSTRAINT CONSTRAINT_69 PRIMARY KEY (RECORD_VALID_DEFN_PID);

ALTER TABLE CONTAIN_NAMES ADD CONSTRAINT CONSTRAINT_5B PRIMARY KEY (CONTAIN_NAME_PID);

ALTER TABLE COMMIT_LOGS ADD CONSTRAINT CONSTRAINT_DC PRIMARY KEY (COMMIT_LOG_PID);

ALTER TABLE BIO_KIN_TERM_DEFNS ADD CONSTRAINT CONSTRAINT_5 PRIMARY KEY (BIO_KIN_TERM_DEFN_PID);

ALTER TABLE COMMIT_ITEMS ADD CONSTRAINT CONSTRAINT_A PRIMARY KEY (COMMIT_ITEM_PID);

ALTER TABLE FIELD_VALID_DEFNS ADD CONSTRAINT CONSTRAINT_3E PRIMARY KEY (FIELD_VALID_DEFN_PID);

ALTER TABLE THEME_DEFNS ADD CONSTRAINT CONSTRAINT_AC PRIMARY KEY (THEME_DEFN_PID);

ALTER TABLE DIGITAL_NOTEPADS ADD CONSTRAINT CONSTRAINT_9 PRIMARY KEY (DIGITAL_NOTEPAD_PID);

ALTER TABLE TEXT_STYLE_DEFNS ADD CONSTRAINT CONSTRAINT_B7 PRIMARY KEY (TEXT_STYLE_DEFN_PID);

ALTER TABLE FIELD_DATA_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_2D PRIMARY KEY (FIELD_DATA_TYPE_DEFN_PID);

ALTER TABLE SESSIONS ADD CONSTRAINT CONSTRAINT_826 PRIMARY KEY (SESSION_PID);

ALTER TABLE SUBSTN_OTHER_ALIASES ADD CONSTRAINT CONSTRAINT_45 PRIMARY KEY (SUBSTN_OTHER_ALIAS_PID);

ALTER TABLE MEMO_DEFNS ADD CONSTRAINT CONSTRAINT_A8 PRIMARY KEY (MEMO_DEFN_PID);

ALTER TABLE NOTEPAD_DEFNS ADD CONSTRAINT CONSTRAINT_27 PRIMARY KEY (NOTEPAD_DEFN_PID);

ALTER TABLE OCCASN_TAG_DEFNS ADD CONSTRAINT CONSTRAINT_A8B PRIMARY KEY (OCCASN_TAG_DEFN_PID);

ALTER TABLE USER_MESSAGES ADD CONSTRAINT CONSTRAINT_29C PRIMARY KEY (USER_MESSAGE_PID);

ALTER TABLE DIGITAL_NAME_MAPS ADD CONSTRAINT CONSTRAINT_17 PRIMARY KEY (DIGITAL_NAME_MAP_PID);

ALTER TABLE SENTENCE_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_1D3 PRIMARY KEY (SENTENCE_TYPE_DEFN_PID);

ALTER TABLE SUBSET_BIO_NETWORK_DEFNS ADD CONSTRAINT CONSTRAINT_6D PRIMARY KEY (SUBSET_BIO_NETWORK_DEFN_PID);

ALTER TABLE OCCASN_NAME_PARTS ADD CONSTRAINT CONSTRAINT_F3 PRIMARY KEY (OCCASN_NAME_PART_PID);

ALTER TABLE ROLE_NAME_TRANS ADD CONSTRAINT CONSTRAINT_D9 PRIMARY KEY (ROLE_NAME_TRAN_PID);

ALTER TABLE OCCASN_NOTEPADS ADD CONSTRAINT CONSTRAINT_7F PRIMARY KEY (OCCASN_NOTEPAD_PID);

ALTER TABLE CITN_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_DA PRIMARY KEY (CITN_TYPE_DEFN_PID);

ALTER TABLE BIO_KIN_TERM_TRANS ADD CONSTRAINT CONSTRAINT_5F PRIMARY KEY (BIO_KIN_TERM_TRAN_PID);

ALTER TABLE PHYSICALS ADD CONSTRAINT CONSTRAINT_828 PRIMARY KEY (PHYSICAL_PID);

ALTER TABLE REMINDER_TRANS ADD CONSTRAINT CONSTRAINT_D0 PRIMARY KEY (REMINDER_TRAN_PID);

ALTER TABLE FLAG_DEFNS ADD CONSTRAINT CONSTRAINT_8 PRIMARY KEY (FLAG_DEFN_PID);

ALTER TABLE BIO_NAME_MAPS ADD CONSTRAINT CONSTRAINT_3A PRIMARY KEY (BIO_NAME_MAP_PID);

ALTER TABLE HDATE_DATE_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_1D PRIMARY KEY (HDATE_DATE_TYPE_DEFN_PID);

ALTER TABLE NAME_STYLE_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_C6 PRIMARY KEY (NAME_STYLE_TYPE_DEFN_PID);

ALTER TABLE HINTERVALS ADD CONSTRAINT CONSTRAINT_78 PRIMARY KEY (HINTERVAL_PID);

ALTER TABLE SEX_DEFNS ADD CONSTRAINT CONSTRAINT_E7 PRIMARY KEY (SEX_DEFN_PID);

ALTER TABLE SENTENCE_SET_DEFNS ADD CONSTRAINT CONSTRAINT_1C PRIMARY KEY (SENTENCE_SET_DEFN_PID);

ALTER TABLE SUBSTN_TEMPLATES ADD CONSTRAINT CONSTRAINT_2F PRIMARY KEY (SUBSTN_TEMPLATE_PID);

ALTER TABLE OCCASNS ADD CONSTRAINT CONSTRAINT_C9 PRIMARY KEY (OCCASN_PID);

ALTER TABLE DIGITALS ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY (DIGITAL_PID);

ALTER TABLE OCCASN_OCCASN_TAG_DEFNS ADD CONSTRAINT CONSTRAINT_60 PRIMARY KEY (OCCASN_OCCASN_TAG_DEFN_PID);

ALTER TABLE OCCASN_TIMELINE_ELMNTS ADD CONSTRAINT CONSTRAINT_84 PRIMARY KEY (OCCASN_TIMELINE_ELMNT_PID);

ALTER TABLE HINTERVAL_MODIFIER_DEFNS ADD CONSTRAINT CONSTRAINT_23 PRIMARY KEY (HINTERVAL_MODIFIER_DEFN_PID);

ALTER TABLE TABLE_DEFNS ADD CONSTRAINT CONSTRAINT_DA3 PRIMARY KEY (TABLE_DEFN_PID);

ALTER TABLE OCCASN_BTWN_ASSOCS ADD CONSTRAINT CONSTRAINT_B1D PRIMARY KEY (OCCASN_BTWN_ASSOC_PID);

ALTER TABLE SUBSET_MIX_DEFNS ADD CONSTRAINT CONSTRAINT_29 PRIMARY KEY (SUBSET_MIX_DEFN_PID);

ALTER TABLE SCRIPT_GROUP_DEFNS ADD CONSTRAINT CONSTRAINT_630 PRIMARY KEY (SCRIPT_GROUP_DEFN_PID);

ALTER TABLE MESSAGE_TEMPLATE_DEFNS ADD CONSTRAINT CONSTRAINT_77 PRIMARY KEY (MESSAGE_TEMPLATE_DEFN_PID);

ALTER TABLE SUBSTN_COMMON_DEFNS ADD CONSTRAINT CONSTRAINT_8C PRIMARY KEY (SUBSTN_COMMON_DEFN_PID);

ALTER TABLE SENTENCE_STYLE_DEFNS ADD CONSTRAINT CONSTRAINT_BF PRIMARY KEY (SENTENCE_STYLE_DEFN_PID);

ALTER TABLE LANGUAGE_NAME_TRANS ADD CONSTRAINT CONSTRAINT_F PRIMARY KEY (LANGUAGE_NAME_TRAN_PID);

ALTER TABLE PROJECTS ADD CONSTRAINT CONSTRAINT_F31 PRIMARY KEY (PROJECT_PID);

ALTER TABLE SUBSTN_FILTER_DEFNS ADD CONSTRAINT CONSTRAINT_46 PRIMARY KEY (SUBSTN_FILTER_DEFN_PID);

ALTER TABLE DISPLAY_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_B1 PRIMARY KEY (DISPLAY_TYPE_DEFN_PID);

ALTER TABLE USER_GROUP_RIGHTS_DEFNS ADD CONSTRAINT CONSTRAINT_50 PRIMARY KEY (USER_GROUP_RIGHTS_DEFN_PID);

ALTER TABLE FIELD_FORMAT_DEFNS ADD CONSTRAINT CONSTRAINT_24 PRIMARY KEY (FIELD_FORMAT_DEFN_PID);

ALTER TABLE FLAG_STATE_DEFNS ADD CONSTRAINT CONSTRAINT_C7 PRIMARY KEY (FLAG_STATE_DEFN_PID);

ALTER TABLE LIFE_PHASE_DEFNS ADD CONSTRAINT CONSTRAINT_F5 PRIMARY KEY (LIFE_PHASE_DEFN_PID);

ALTER TABLE TAG_GROUP_DEFNS ADD CONSTRAINT CONSTRAINT_CE5 PRIMARY KEY (TAG_GROUP_DEFN_PID);

ALTER TABLE OCCASN_OCCASNS ADD CONSTRAINT CONSTRAINT_A7 PRIMARY KEY (OCCASN_OCCASN_PID);

ALTER TABLE BIO_NAMES ADD CONSTRAINT CONSTRAINT_D PRIMARY KEY (BIO_NAME_PID);

ALTER TABLE BIO_NAME_PARTS ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY (BIO_NAME_PART_PID);

ALTER TABLE CITATIONS ADD CONSTRAINT CONSTRAINT_3C PRIMARY KEY (CITATION_PID);

ALTER TABLE USER_GROUP_DEFNS ADD CONSTRAINT CONSTRAINT_21 PRIMARY KEY (USER_GROUP_DEFN_PID);

ALTER TABLE BIO_NOTEPADS ADD CONSTRAINT CONSTRAINT_6 PRIMARY KEY (BIO_NOTEPAD_PID);

ALTER TABLE USERS ADD CONSTRAINT CONSTRAINT_4D PRIMARY KEY (USER_PID);

ALTER TABLE SUBSTN_TEMPLATE_DEFNS ADD CONSTRAINT CONSTRAINT_B13 PRIMARY KEY (SUBSTN_TEMPLATE_DEFN_PID);

ALTER TABLE TEMPLATE_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_E76 PRIMARY KEY (TEMPLATE_TYPE_DEFN_PID);

ALTER TABLE SUBSTN_PARAM_NAMES ADD CONSTRAINT CONSTRAINT_6D0 PRIMARY KEY (SUBSTN_PARAM_NAME_PID);

ALTER TABLE CONTAIN_NAME_PARTS ADD CONSTRAINT CONSTRAINT_B PRIMARY KEY (CONTAIN_NAME_PART_PID);

ALTER TABLE PHYSICAL_NAME_MAPS ADD CONSTRAINT CONSTRAINT_40 PRIMARY KEY (PHYSICAL_NAME_MAP_PID);

ALTER TABLE VIEWPOINT_ELEMENTS ADD CONSTRAINT CONSTRAINT_7A0 PRIMARY KEY (VIEWPOINT_ELEMENT_PID);

ALTER TABLE FIELD_DEFNS ADD CONSTRAINT CONSTRAINT_DF PRIMARY KEY (FIELD_DEFN_PID);

ALTER TABLE BIO_PARENT_SETS ADD CONSTRAINT CONSTRAINT_C PRIMARY KEY (BIO_PARENT_SET_PID);

ALTER TABLE NAME_ELMNT_TYPE_DEFNS ADD CONSTRAINT CONSTRAINT_5BD PRIMARY KEY (NAME_ELMNT_TYPE_DEFN_PID);

ALTER TABLE BIO_ETHNICITY_DEFNS ADD CONSTRAINT CONSTRAINT_3 PRIMARY KEY (BIO_ETHNICITY_DEFN_PID);

ALTER TABLE SUBSET_DEFNS ADD CONSTRAINT CONSTRAINT_FC PRIMARY KEY (SUBSET_DEFN_PID);


