SELECT PUBLIC.LABEL_TRANS.ABBREV, PUBLIC.LABEL_TRANS.NAME, PUBLIC.LABEL_TRANS.DESCRIPTION
  FROM PUBLIC.LABEL_TRANS, PUBLIC.SEX_DEFNS
  WHERE PUBLIC.LABEL_TRANS.TABLE_KEY = 407
    AND PUBLIC.LABEL_TRANS.RECORD_PID = 
    (SELECT SEX_KEY FROM BIOS
    WHERE BIO_PID = 1);
SELECT BEST_NAME_PID FROM BIOS 
WHERE BIO_PID = 1;