--<ScriptOptions statementTerminator=";"/>

ALTER TABLE BIOS DROP CONSTRAINT CONSTRAINT_1F;

DROP INDEX PRIMARY_KEY_1F;

DROP TABLE BIOS;

CREATE TABLE BIOS (
		RECORD_NUM INTEGER NOT NULL,
		SET_KEY SMALLINT NOT NULL,
		COMMIT_PID INTEGER NOT NULL,
		BIO_PID INTEGER NOT NULL,
		IS_SYSTEM BOOLEAN,
		VISIBLE_ID INTEGER NOT NULL,
		SUB_TYPE_KEY SMALLINT,
		BEST_NAME_PID INTEGER,
		BEST_BIRTH_PID INTEGER,
		BEST_DEATH_PID INTEGER,
		BEST_BIO_MALE_PARENT_PID INTEGER,
		BEST_BIO_FEMALE_PARENT_PID INTEGER,
		USE_BIO_MALE_PARENT BOOLEAN,
		USE_BIO_FEMALE_PARENT BOOLEAN,
		BEST_NON_BIO_PARENT1_PID INTEGER,
		BEST_NON_BIO_PARENT2_PID INTEGER,
		BEST_IMAGE_PID INTEGER,
		SEX_KEY SMALLINT,
		LIVING_KEY SMALLINT,
		SPERM_PROVIDER_ISSUE_ORDER SMALLINT,
		EGG_PROVIDER_ISSUE_ORDER SMALLINT,
		SURETY VARCHAR(10),
		FLAGS VARBINARY(100)
	);

CREATE UNIQUE INDEX PRIMARY_KEY_1F ON BIOS (BIO_PID ASC);

ALTER TABLE BIOS ADD CONSTRAINT CONSTRAINT_1F PRIMARY KEY (BIO_PID);

